### ISSUE TITLE
When pnpm is set up according to the linked guide, I cannot add dependencies

### ISSUE THREAD

**Issue by jp06** [bigcommerce/b2b-buyer-portal#12]
I wanted to try pnpm so I followed this guide in the documentation to replace the package manager with it: https://dev.to/andreychernykh/yarn-npm-to-pnpm-migration-guide-2n04

It worked well at first, but the time come when I have to add a dependency, it failed with this error like this:
```
@b3/global-b3 is not in the npm registry, or you have no permission to fetch it.
```

It seems like it's trying to fetch from a external private npm registry? I could be wrong. I had to add workspace protocol for the dependencies to try to point them to the local workspace to be able to add a package from npm.

For example, for all dependencies referenced from `packages/*` (everything seems to have version set as `*`):
```json
  "dependencies": {
    "@b3/global-b3": "*",
```
I changed to:
```json
  "dependencies": {
    "@b3/global-b3": "workspace:*",
```

I cannot remember if I ran `pnpm i` after the manual changes, I might have.

And to add a package to the storefront repo, you have to add a filter flag to specify that you're installing for a certain package only. For example, I wanted to add a library to the `storefront` package (in the `app/storefront`) folder:
```
pnpm add -F storefront <npm_package>
```

I haven't yet worked extensively in a monorepo setup and pnpm, for all I know these might be obvious things to deal with. I haven't tried adding a dependency with Yarn if it also has this issue. I know the current setup is with Yarn but just wondering if these could be clarified in the documentation on the part regarding changing to pnpm.

**Comment by bc-marco** [comment]
Thanks for the report, we have been reviewing it and yes, there are problems on this, so for the moment please use `yarn`

We will work on the future to provide a better migration guide

**Comment by jp06** [comment]
Just to note that I had some more issues using pnpm. Cannot remember well now, but  it has something to do with dependencies and issue with resolving of modules and types. Probably due to hoisting in yarn vs pnpm. More trouble maintaining when trying to merge upstream code so going back to yarn.
