### ISSUE TITLE
 "Signature verification failed" error when trying to login as a user from the admin area of a BC store

### ISSUE THREAD

**Issue by cjsanchezBW** [bigcommerce/b2b-buyer-portal#24]
**Please fill out this template to help us diagnose and address your issue effectively.**

**Type:** (Select one)
- [X] Bug Report
- [ ] Feature Request

**Summary:**

* Briefly describe the issue or feature request.
Platform is BigCommerce (not headless). Login as user not working for the open source version of Buyer portal.
**Expected Behavior:**
* Describe what you expect to happen under normal circumstances.
Logging in as a user via the admin area should allow you to navigate the website as if you had logged in normally as that user.
**Actual Behavior:**
From the BC admin go to the customers section and login as a user. You will see it's not possible to login.

* Describe what is actually happening. 
Cant access buyer portal pages after logging in as a user from the BC admin.

**Steps to Reproduce (Bug Reports Only):**

   1. List the specific steps necessary to reproduce the bug.

1 -Build the buyer portal code as instructed in the read me. Then deploy to the store's webdav.
2 - Try to login as a user via the admin area.
3- The app produces a blank loading screen and gets stuck

**Additional Information:**

* Include any other relevant details that might help us understand the issue.
Tested using chrome and firefox on windows.

**Backend Request Information (Optional):**

There's a graphQL request that comes back with an error when you attempt to log in as a user. We found that the same error comes up if you open a new tab and attempt to open to buyer portal.

   - If the issue involves interaction with a backend API, please provide details about the request:
      - API endpoint URL
      -https://api-b2b.bigcommerce.com/graphql

      - HTTP method (GET, POST, PUT, DELETE, etc.)
      Post
      - Request body (if applicable)
      {
    "query": "mutation {\n\tauthorization(authData: {\n\t\tbcToken: \"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJjdXN0b21lciI6eyJpZCI6MTEsImVtYWlsIjoic3RraXR6cm93QGJyaWxsaWFuY2V3ZWIuY29tIiwiZ3JvdXBfaWQiOiIxIn0sImlzcyI6ImJjL2FwcHMiLCJzdWIiOiJsemQzaGwxdXhjIiwiaWF0IjoxNzE3NTg4NjE0LCJleHAiOjE3MTc1ODk1MTQsInZlcnNpb24iOjEsImF1ZCI6InF4dmFwd2xrNGZiYjlkeW9nZGN4azlvNTBkOWpxam8iLCJhcHBsaWNhdGlvbl9pZCI6InF4dmFwd2xrNGZiYjlkeW9nZGN4azlvNTBkOWpxam8iLCJzdG9yZV9oYXNoIjoibHpkM2hsMXV4YyIsIm9wZXJhdGlvbiI6ImN1cnJlbnRfY3VzdG9tZXIifQ.oEKTnF3hl45TiTZCTaU5f2O8C2O_YikAg6Jvge4hPIr1Qv1JMl6LvwrUe8t7EneUYObN_TQ3Ch1C0QaZVRtukA\"\n\t\tchannelId: 1\n\t}) {\n\t\tresult {\n\t\t\ttoken\n\t\t\tloginType\n\t\t}\n\t}\n}"
}

- Request response:

{
    "message": "Signature verification failed",
    "locations": [
        {
            "line": 2,
            "column": 2
        }
    ],
    "path": [
        "authorization"
    ]
}

**Version:**

* Specify the version of your project you are using.
A slightly modified version of the latest code in master. And we also tried a slightly modified version of the 2.0.0 tag
**Screenshots/Screen Recordings (Optional):**

* Attach any screenshots or screen recordings that illustrate the issue.

**Thank you for your report! We appreciate your contribution to improving our project.**

**Comment by bc-marco** [comment]
@cjsanchezBW do you have any updates with your issue?

**Comment by cjsanchezBW** [comment]
@bc-marco We tried what you suggested and it worked. We were able to move forward. Thanks.

**Comment by cjsanchezBW** [comment]
closing.
