### ISSUE TITLE
I had difficulties connecting to the buyer portal when I tried to deploy the application locally.

### ISSUE THREAD

**Issue by iyarovoy-igor** [bigcommerce/b2b-buyer-portal#25]
Type: Bug Report

Summary:

I had difficulties connecting to the buyer portal when I tried to deploy the application locally.
Issue report or feature request:

**Configuration I added:**

1. added the scripts to the header and footer in the stencil theme locally  (the same as provided in the documentation)
2. changed the env file: here is the question about app_client _d, I use 

`VITE_B2B_CLIENT_ID=dl7c39mdpul6hyc489yk0vzxl6jesyx`

This ID is provided by the b2b edition doc (https://developers.bundleb2b.com/docs/openapi/auth). Please let me know if I need another one, and if so how to get it.

`VITE_STORE_HASH="zpaqzjvja6"`

This is the store hash of my store. 

I don't know the absolute path, and if it is needed for local development. (I run yarn prod build and set the path to the dist folder)

`VITE_ASSETS_ABSOLUTE_PATH="http://localhost:3001/apps/storefront/dist/assets"`

The issue I had. 
1. I run stencil locally on port 4000
2. I run the buyer portal locally on port 3001
3. I click on the account page in Stencil and get an infinite loading of the page and some errors like:

![image](https://github.com/bigcommerce/b2b-buyer-portal/assets/125443989/a9fcd8c0-8883-4ff5-98f5-2a1f0212b23a)

So I see that the storefront is connected to the buyer portal but there is some misconfiguration.

Please let me know if there is some mistake in the configuration and provide more detailed instructions on how to connect these to apps.

**Comment by bc-marco** [comment]
Hello @iyarovoy-igor 

We have created a PR to updated the setup guide, please read the new changes [on this PR](https://github.com/bigcommerce/b2b-buyer-portal/pull/27/files)

**Comment by bc-marco** [comment]
Hi @iyarovoy-igor 
Is there any update on this? We have already updated the setup guide, it will help use a lot your feedback

**Comment by iyarovoy-igor** [comment]
Hi!

I apologize for the long response.

I will be able to setup the application on Monday.

Thank you for your help.

**Comment by iyarovoy-igor** [comment]
@bc-marco Hi! 

Using the new setup guide, I was able to run the app locally.

Thank you!

**Comment by iyarovoy-igor** [comment]
Hi!

Using the new setup guide, I was able to run the app locally.

Thank you!

**Comment by bc-marco** [comment]
Excellent!
Closing this issue as is not longer present
