### ISSUE TITLE
"Deploying the project" GET https://br.storage.bunnycdn.com/assets/react-setup-CAzFZYyQ.js net::ERR_ABORTED 401 (Unauthorized)

### ISSUE THREAD

**Issue by pocimadigital-sergio** [bigcommerce/b2b-buyer-portal#45]
Type: Implementation error

Summary:
Unable to access URLs declared in my index.*.js when deploying the "b2b-buyer-portal".

Expected Behavior:
I expect that the URLs declared in index.*.js (listed below) should be accessible and loaded correctly:

    https://br.storage.bunnycdn.com/assets/react-setup-CAzFZYyQ.js
    https://br.storage.bunnycdn.com/assets/b3Logger-CMQiGC3f.js
    https://br.storage.bunnycdn.com/assets/react-setup-C6kNScU8.css

Actual Behavior:
The URLs declared in index.*.js are not being accessed or loaded correctly by the application.

Steps to Reproduce:

"Deploying the project"
    Deploy the "b2b-buyer-portal": yarn build:production
    Create a footer script.
    Create a header script.
    "Replace <YOUR_APP_URL_HERE> with the URL where your build is hosted, <YOUR_STORE_HASH> and <YOUR_CHANNEL_ID> with its respective values. Replace the * in the file names with the generated hash from the build step."

line of index.*.js:
const __vite__fileDeps = [
  "https://br.storage.bunnycdn.com/assets/react-setup-CAzFZYyQ.js",
  "https://br.storage.bunnycdn.com/assets/b3Logger-CMQiGC3f.js",
  "https://br.storage.bunnycdn.com/assets/react-setup-C6kNScU8.css"
];

I have loaded my "dist" manually, since when running yarn build:production it does not save it in my VITE_ASSETS_ABSOLUTE_PATH, maybe that is related?

Screenshots/Screen Recordings:
![image](https://github.com/bigcommerce/b2b-buyer-portal/assets/128639278/586d726e-0e4d-4e93-ae2b-f69225d40fba)

**Comment by bc-victor** [comment]
Hello @pocimadigital-sergio,

Thank you for reporting this issue. The 401 Unauthorized error typically indicates a problem with authentication or permissions when accessing the URLs on your CDN. Here are some steps to help you resolve this issue:

Authentication Token:
Ensure that the correct authentication token is being used to access the BunnyCDN URLs. BunnyCDN requires an API key for authentication. Verify that the token has the necessary permissions to access the specified resources.

CORS Settings:
Check the CORS (Cross-Origin Resource Sharing) settings on BunnyCDN. Make sure that your domain is allowed to access the resources hosted on BunnyCDN.

URL Validity:
Double-check the URLs in your index.*.js file to ensure they are correct and not expired. Any changes in the file names or paths will cause the URLs to be inaccessible.

Access Permissions:
Verify the access permissions on the BunnyCDN storage. Ensure that the files are set to public or that the access control settings are correctly configured to allow access from your application.

Attaching screenshot reproducing th error:

<img width="1512" alt="Screenshot 2024-06-18 at 11 36 55 a m" src="https://github.com/bigcommerce/b2b-buyer-portal/assets/140021227/66ccf44b-90f7-42ae-9b16-1bac877fe5e6">

**Comment by bc-victor** [comment]
Here's an example of the production build of B2B Edition, it is publicly accessible without authentication https://cdn.bundleb2b.net/b2b/production/storefront/index.0702c89f.js


<img width="1624" alt="Screenshot 2024-06-18 at 12 02 49 p m" src="https://github.com/bigcommerce/b2b-buyer-portal/assets/140021227/a1358a4b-2215-42f0-905f-62f9cd2f9727">

**Comment by pocimadigital-sergio** [comment]
Finally I chose to repeat the entire process. When cloning the repository again and following the steps, notice that my generated dist is different from the previous one, modifying this:
const __vite__fileDeps = [
"https://br.storage.bunnycdn.com/assets/react-setup-CAzFZYyQ.js",
"https://br.storage.bunnycdn.com/assets/b3Logger-CMQiGC3f.js",
"https://br.storage.bunnycdn.com/assets/react-setup-C6kNScU8.css"
];
For this:
const __vite__fileDeps=[
"/react-setup-DjgN3Y_p.js",
"/b3Logger-CMQiGC3f.js",
"/react-setup-C6kNScU8.css"
];

In this sense, by being located locally, I have control over them.

For my part, this issue is resolved.
