### ISSUE TITLE
 S.split is not a function

### ISSUE THREAD

**Issue by SunilP-WassDigital** [bigcommerce/b2b-buyer-portal#49]
Hello,

when you open some time , when you click on user menu for login getting below error
 S.split is not a function

![image](https://github.com/bigcommerce/b2b-buyer-portal/assets/169963266/cae280d1-10c5-4ab1-8af3-d5bb230fc296)

I m getting SVGAnimatedString, it should be get href of user link

**Comment by bc-marco** [comment]
Hello @SunilP-WassDigital 

Please fill the provided template, it help us to bring you the best support

I'll close as is not providing enough context
