### ISSUE TITLE
Navigation Menu showing disabled features

### ISSUE THREAD

**Issue by SE-Graham** [bigcommerce/b2b-buyer-portal#61]
**Type:** (Select one)
- [x] Bug Report
- [ ] Feature Request

**Summary:**

The navigation menu is showing features that have been disabled e.g you turn invoices off in the b2b app in BC.

The issue seems to have been caused by changes made in bdcda35c2b21d4191fde5eb951fd8f35b9be97f1 

The following was added to the routes - getAllowedRoutes this seems to skip checking if features are enabled and only check permissions
```
    // b2b user
     if (isB2BUser && permissionCodes && permissionCodes.length > 0) {
       const permissionsInfo: {
         code: string;
         permissionLevel?: number | string;
       } = {
         code: permissionCodes.join(','),
       };
       const isHasPermission = checkEveryPermissionsCode(permissionsInfo);

       if (path === '/company-orders' && isHasPermission) {
         let companyOrdersPermissions: boolean = isHasPermission;

         const myOrdersLevel = 1;
         permissionsInfo.permissionLevel = myOrdersLevel;

         companyOrdersPermissions = !checkEveryPermissionsCode(permissionsInfo);

         return companyOrdersPermissions;
       }

       return isHasPermission;
     }
```

**Expected Behavior:**

* Don't show disabled features in the navigation menu when they have been disabled.

**Actual Behavior:**

* Disabled features are showing in the navigation menu 

* Describe what is actually happening. 

**Steps to Reproduce (Bug Reports Only):**

   1. Disable Invoices
   2. Load Buyer Portal, Invoices are still on the navigation menu

**Comment by SE-Graham** [comment]
Does this PR https://github.com/bigcommerce/b2b-buyer-portal/pull/67 resolve this issue?

**Comment by deov31** [comment]
@SE-Graham yes, that one is related to this issue

**Comment by SE-Graham** [comment]
Closing as this was resolved with PR https://github.com/bigcommerce/b2b-buyer-portal/pull/67
