### ISSUE TITLE
Issue report: Persist cart not working while using buyer portal 

### ISSUE THREAD

**Issue by cjsanchezBW** [bigcommerce/b2b-buyer-portal#73]
**Please fill out this template to help us diagnose and address your issue effectively.**

**Type:** (Select one)
- [x] Bug Report

**Summary:**

* Briefly describe the issue or feature request.

**Expected Behavior:**

* Describe what you expect to happen under normal circumstances.
I should be able to see my cart accross different devices and even if I log out and log back into the website.

**Actual Behavior:**

* Describe what is actually happening. 
Cart contents are not persistent.

**Steps to Reproduce (Bug Reports Only):**

   1. List the specific steps necessary to reproduce the bug.
   I log in as a user who can add items to cart. I add an item to the cart. I log out. I log back in. My cart is empty

**Additional Information:**

* Include any other relevant details that might help us understand the issue.
   - Browser version (e.g., Chrome 110, Firefox 108)
   Tested using Chrome 126
   - OS version (e.g., Windows 11, macOS Monterey)
   -Windows 11
   - Any third-party libraries or dependencies used (versions if possible)
   Tested a clean copy of the repo

**Version:**

* Specify the version of your project you are using.
I tested the latest code available in the main branch

**Comment by cjsanchezBW** [comment]
I looked through the code and found that in the apps\storefront\src\pages\Login\index.tsx file, in line 131, there's a block of code that runs a deleteCart function when the user logs out. 

I am working on a customized buyer portal. For my project we do want the persisted cart to work. Would it cause issues to remove that code that deletes the cart at logout?

**Comment by bc-victor** [comment]
@cjsanchezBW The carts are deleted by default because I'm afraid you'll still lose the cart after 1 re-login. This is a known issue within the BCs storefront APIs that is currently in the feature request status. Closing since this is just not supported yet

**Comment by cjsanchezBW** [comment]
@bc-victor What do you mean by: "The carts are deleted by default because I'm afraid you'll still lose the cart after 1 re-login."

I tested removing the code that deletes the cart and I was able to logout and back in and keep my cart's contents without issues.

apps\storefront\src\pages\Login\index.tsx file, in line 131

**Comment by bc-victor** [comment]
@cjsanchezBW according to our research, these carts will be lost between authentication processes. If your findings are persistent throughout your development please let us know so I can file this behaviour

**Comment by SunilP-WassDigital** [comment]
@cjsanchezBW if i remove code await deleteCart(deleteQuery);  on same browser it is working fine
But let's example , i m doing logout and then open incognito window and login with same user, it should be preserve same cart but does not doing that.

**Comment by adrianWPSG** [comment]
@bc-victor  where can we see the status of the feature request?
