### ISSUE TITLE
VITE_ASSETS_ABSOLUTE_PATH meaning?

### ISSUE THREAD

**Issue by sunilit42** [bigcommerce/b2b-buyer-portal#9]
Hello,

VITE_ASSETS_ABSOLUTE_PATH - can you please specify which path i need to specify? Do i need so specifiy of path of B2b package or theme bundle path URL?

**Comment by bc-victor** [comment]
Hello @sunilit42 - This variable is for you to add your hosting domain when building the project for deployment, you can see more details in this section of the README:

https://github.com/bigcommerce/b2b-buyer-portal?tab=readme-ov-file#deploying-the-project

**Comment by sunilit42** [comment]
@bc-victor Thanks for reply. for local which value i need to set? as i see that value when we do deploy on server

**Comment by bc-victor** [comment]
@sunilit42 For local development the value is not used, therefore the value is irrelevant
