### ISSUE TITLE
Upgrade documentation without self-hosting

### ISSUE THREAD

**Issue by dio5** [bigcommerce/b2b-buyer-portal#93]
Information on upgrading from b2b stencil edition.

We are looking to upgrade to b2b-buyer portal but information on how to migrate while keeping existing extensions/code working and NOT having to self-host is limited.

There used to be a way of injection https://developer.bundleb2b.net/storefront/js.html - where we could grab the instance which then gave us access to various company info.

But I can't see any current equivalent?

There is a b2b variable but it doesn't seem to be as extensive and no documentation.

![Screenshot from 2024-08-12 16-17-01](https://github.com/user-attachments/assets/557cffb5-8838-4f4a-8fb0-c09e1df04c19)

Is the only way now to self-host and change/extend the code, or maybe to get the token and then make the new necessary calls from the theme? We are doing various tweaks in the theme/cart that use b2b info.

**Comment by bc-victor** [comment]
@dio5 There is currently no upgrade guide or util. The buyer portal and the stencil theme do not share logic and are treated as isolated application entities
