### ISSUE TITLE
Disabled Product  still available in customer's shopping list.

### ISSUE THREAD

**Issue by SunilP-WassDigital** [bigcommerce/b2b-buyer-portal#95]
**Please fill out this template to help us diagnose and address your issue effectively.**

**Type:** (Select one)
- [ ] Bug Report

**Summary:**
- login as B2b users
- add item add into shopping list
- then Visible on Storefront set to false
- then check shopping list, it should be remove that time

**Expected Behavior:**

- Disabled product should not be show on fronted side

**Actual Behavior:**
- showing product on shopping list

**Comment by bc-marco** [comment]
Thanks for raising this issue and taking the time to report it.

We understand your concern about the current behavior of the availability of a product to be purchased even if this has visibility set to `false`. However, this behavior is actually intended.

To achieve the desired outcome of preventing purchases on a specific product, we recommend configuring the product as "non-purchasable." This will effectively remove the product from the purchasing options, aligning with your intended use case.

While we appreciate your suggestion, we won't be implementing a specific change to address this particular scenario at this time.

Please let us know if you have any other questions or concerns.
